import { NextResponse } from "next/server";
import { dbConnect } from "@/lib/db/mongoose";
import Admin from "@/models/Admin";
import Article from "@/models/Article";
import Video from "@/models/Video";

export async function GET() {
  try {
    await dbConnect();

    // Ensure we have a super_admin to link as the author
    let admin = await Admin.findOne({ role: "super_admin" });
    if (!admin) {
      // If the admin seed wasn't run, create a dummy one just for linking
      admin = await Admin.create({
        username: "system_seeder",
        password: "dummy_password",
        email: "seeder@asitrack.com",
        role: "super_admin",
      });
    }

    const adminId = admin._id;

    // --- SEED ARTICLES ---
    const articles = [
      {
        title: "Posisi Pelekatan (Latch On) yang Benar Saat Menyusui",
        content: `
          <p>Pelekatan (latch on) yang benar adalah kunci utama agar ibu tidak merasa nyeri dan bayi mendapatkan ASI secara optimal. Posisi yang salah sering kali menjadi penyebab utama puting lecet dan produksi ASI yang terasa kurang.</p>
          <h3>Tanda-tanda Pelekatan yang Baik:</h3>
          <ul>
            <li>Dagu bayi menempel pada payudara ibu.</li>
            <li>Mulut bayi terbuka lebar, bibir bawah terlipat keluar (dower).</li>
            <li>Sebagian besar areola (area gelap di sekitar puting) masuk ke dalam mulut bayi, terutama areola bagian bawah.</li>
            <li>Pipi bayi tampak membulat saat menghisap.</li>
            <li>Terdengar suara menelan yang pelan, bukan suara mengecap (klik).</li>
          </ul>
          <p>Jangan ragu untuk melepaskan isapan bayi dengan memasukkan kelingking bersih ke sudut mulutnya jika terasa sakit, lalu ulangi proses pelekatan dari awal.</p>
        `,
        excerpt: "Pelekatan (latch on) yang benar adalah kunci utama agar ibu tidak merasa nyeri dan bayi mendapatkan ASI secara optimal...",
        cover_image_url: "/images/articles/latch_on_cover.png",
        kategori: "Edukasi",
        published: true,
        created_by: adminId,
      },
      {
        title: "Mengenali Tanda Bayi Cukup ASI",
        content: `
          <p>Banyak ibu baru merasa khawatir apakah bayi mereka mendapatkan cukup ASI, mengingat kita tidak bisa menakar volumenya seperti susu formula. Jangan panik, Bunda. Ada beberapa tanda objektif yang bisa diamati.</p>
          <h3>Tanda Bayi Cukup ASI:</h3>
          <ul>
            <li><strong>Buang Air Kecil (BAK):</strong> Bayi pipis setidaknya 6 kali sehari setelah usia 4-5 hari. Warna urin jernih atau kuning muda.</li>
            <li><strong>Buang Air Besar (BAB):</strong> BAB berwarna kuning terang dengan tekstur berbiji (seedy) setidaknya 3-4 kali sehari.</li>
            <li><strong>Berat Badan:</strong> Setelah penurunan fisiologis di minggu pertama, berat badan bayi akan mulai naik dan kembali ke berat lahir pada usia 10-14 hari.</li>
            <li><strong>Kondisi Bayi:</strong> Bayi tampak puas, rileks, dan sering tertidur dengan sendirinya setelah menyusu. Payudara ibu juga terasa lebih kosong dan lembut setelah menyusui.</li>
          </ul>
          <p>Tetap tenang dan susui bayi semau bayi (on demand), minimal 8-12 kali dalam 24 jam.</p>
        `,
        excerpt: "Banyak ibu baru merasa khawatir apakah bayi mereka mendapatkan cukup ASI. Jangan panik, Bunda, amati tanda-tanda berikut...",
        cover_image_url: "/images/articles/cukup_asi_cover.png",
        kategori: "Kesehatan Bayi",
        published: true,
        created_by: adminId,
      }
    ];

    // Delete existing dummy articles to avoid duplicates
    await Article.deleteMany({ title: { $in: articles.map(a => a.title) } });
    await Article.insertMany(articles);

    // --- SEED VIDEOS ---
    const videos: Array<{
      title: string;
      youtube_url: string;
      kategori: "relaksasi" | "terapi";
      deskripsi: string;
      published: boolean;
      created_by: any;
    }> = [
      {
        title: "Musik Relaksasi Gelombang Delta untuk Ibu Hamil & Menyusui",
        youtube_url: "https://www.youtube.com/watch?v=FjHGZj2IjKd", // Placeholder example url
        kategori: "relaksasi",
        deskripsi: "Musik relaksasi dengan gelombang delta yang dirancang khusus untuk menurunkan hormon stres (kortisol) dan merangsang hormon oksitosin agar ASI lebih lancar.",
        published: true,
        created_by: adminId,
        // youtube_id and thumbnail_url are automatically generated by the pre-validate hook in the schema, but insertMany bypasses hooks unless specified, so we'll use create()
      },
      {
        title: "Tutorial Pijat Oksitosin untuk Memperlancar ASI",
        youtube_url: "https://www.youtube.com/watch?v=vV1p-F_i5Yk", // Placeholder example url
        kategori: "terapi",
        deskripsi: "Panduan lengkap langkah demi langkah melakukan pijat oksitosin di area tulang belakang untuk merangsang refleks let-down ASI. Mintalah bantuan suami untuk melakukan pijatan ini.",
        published: true,
        created_by: adminId,
      }
    ];

    await Video.deleteMany({ title: { $in: videos.map(v => v.title) } });
    
    // Use .create() to trigger mongoose hooks for youtube_id extraction
    for (const vid of videos) {
      await Video.create(vid);
    }

    return NextResponse.json({
      status: "success",
      message: "Data Artikel dan Video berhasil disuntikkan ke database (Seeded).",
    });

  } catch (error: any) {
    console.error("Seeding Education Error:", error);
    return NextResponse.json(
      { status: "error", message: error.message },
      { status: 500 }
    );
  }
}
